### ISSUE TITLE
GET requests should not allow to specify Content-Type

### ISSUE THREAD

**Issue by lfryc** [feedhenry-templates/fh-api-mapper#16]
Since GET requests does not have body, they should not specify `content-type`. The UI may be misleading with `content-type` present for GET requests.

> Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".

via http://stackoverflow.com/questions/5661596/do-i-need-a-content-type-for-http-get-requests

**Comment by lfryc** [comment]
@cianclarke mind to review? :rugby_football:

**Comment by cianclarke** [comment]
Fixed in https://github.com/feedhenry-templates/fh-api-mapper/pull/22
