### ISSUE TITLE
Code samples are not updated

### ISSUE THREAD

**Issue by lfryc** [feedhenry-templates/fh-api-mapper#18]
Node.js / CURL samples are not updated after sending request

**Comment by lfryc** [comment]
Seems that they are not updated when hiting `Send request` button,
but if you `Save request` and then open it, the samples are updated.

@cianclarke I believe the samples should be kept in sync with the model => updated whenever the input update changes, so no `Send` or `Save` would be required, wdyt?

**Comment by cianclarke** [comment]
Fixed in https://github.com/feedhenry-templates/fh-api-mapper/pull/22
