### ISSUE TITLE
Delete request body when saving GET request

### ISSUE THREAD

**Issue by lfryc** [feedhenry-templates/fh-api-mapper#19]
Steps to reproduce:
1. Create new request
2. use POST type and define request body
3. switch to GET and hit save
4. open the saved request and voila, request body is back as it would be POST

**Comment by lfryc** [comment]
1. Create new request
2. use POST type and define request body
3. switch to GET and hit save
4. open the saved request and voila, request body is back as it would be POST

**Comment by cianclarke** [comment]
Fixed in https://github.com/feedhenry-templates/fh-api-mapper/pull/22
